title: la bonne soupe
#url: "http://labonnesoupe.org"
url: ""
twitter_username: chrscmpbll
github_username:  chrispcampbell
email: chrispcampbell`at`gmail

google_analytics: UA-3872301-4

plugins:
  - jekyll-feed
  - jekyll-redirect-from

theme: minima

minima:
  date_format: "%B %-d, %Y"

paginate: 1
paginate_path: "/page/:num/"

# By default, jekyll-feed uses `/feed.xml`, but Wordpress uses
# either `?feed=atom` or `/feed`, so let's try the latter
feed:
  path: feed

header_pages:
  - pages/music.md
  - pages/photos.md
  - pages/code.md

exclude:
  - legacy/
  - src/

whitelist:
  - jekyll-redirect-from
