title: la bonne soupe
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: chrscmpbll
github_username:  chrispcampbell
email: chrispcampbell`at`gmail

google_analytics: UA-3872301-4

theme: minima
plugins:
  - jekyll-feed

minima:
  date_format: "%B %-d, %Y"

paginate: 1
paginate_path: "/page/:num/"

header_pages:
  - pages/music.md
  - pages/photos.md
  - pages/code.md

exclude:
  - legacy/
