title: la bonne soupe
#url: "http://labonnesoupe.org"
url: ""
mastodon:
  - username: chrispcampbell
    instance: techhub.social
twitter_username: chrscmpbll
github_username:  chrispcampbell
email: chrispcampbell`at`gmail

google_analytics: UA-3872301-4

# XXX: GitHub Pages doesn't handle trailing slashes correctly
# when the default permalink format is used (will result in 404,
# because it won't redirect to `/<post>.html`).  I had a link to a
# post on my Twitter feed (that I can't change) that included
# the trailing slash, so after migrating from Wordpress to GitHub
# Pages, that link would no longer work.  As a workaround, specify
# a custom permalink that writes the page to `/<post>/index.html`
# which GitHub Pages should be able to handle.
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

theme: minima

minima:
  date_format: "%B %-d, %Y"

paginate: 1
paginate_path: "/page/:num/"

# By default, jekyll-feed uses `/feed.xml`, but Wordpress uses
# either `?feed=atom` or `/feed`, so let's try the latter
feed:
  path: feed

header_pages:
  - pages/music.md
  - pages/photos.md
  - pages/code.md

exclude:
  - legacy/
  - src/
